# Generated by Django 5.0.2 on 2024-02-17 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='berries',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='decor',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='form',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='level',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='title',
        ),
        migrations.RemoveField(
            model_name='cake',
            name='topping',
        ),
        migrations.AlterField(
            model_name='cake',
            name='comment',
            field=models.CharField(default='Без подписи', max_length=50, verbose_name='Комментарий'),
        ),
        migrations.CreateModel(
            name='Berries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berries', models.CharField(choices=[('нет', 'нет'), ('Ежевика', 'Ежевика'), ('Малина', 'Малина'), ('Голубика', 'Голубика'), ('Клубника', 'Клубника')], max_length=20, verbose_name='Ягоды')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.cake', verbose_name='Торт')),
            ],
        ),
        migrations.CreateModel(
            name='Decor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decor', models.CharField(choices=[('нет', 'нет'), ('Фисташки', 'Фисташки'), ('Безе', 'Безе'), ('Фундук', 'Фундук'), ('Пекан', 'Пекан'), ('Маршмеллоу', 'Маршмеллоу'), ('Марципан', 'Марципан')], max_length=20, verbose_name='Декор')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.cake', verbose_name='Торт')),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.CharField(choices=[('не выбрано', 'не выбрано'), ('Круг', 'Круг'), ('Квадрат', 'Квадрат'), ('Прямоугольник', 'Прямоугольник')], max_length=20, verbose_name='Форма')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.cake', verbose_name='Торт')),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('не выбрано', 'не выбрано'), ('1', '1'), ('2', '2'), ('3', '3')], max_length=15, verbose_name='Количество уровней')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.cake', verbose_name='Торт')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topping', models.CharField(choices=[('не выбрано', 'не выбрано'), ('Без', 'Без'), ('Белый соус', 'Белый соус'), ('Карамельный', 'Карамельный'), ('Кленовый', 'Кленовый'), ('Черничный', 'Черничный'), ('Молочный шоколад', 'Молочный шоколад'), ('Клубничный', 'Клубничный')], max_length=20, verbose_name='Топпинг')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.cake', verbose_name='Торт')),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words', models.TextField(blank=True, max_length=100, verbose_name='Поздравительные слова')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.cake', verbose_name='Торт')),
            ],
        ),
    ]
