# Generated by Django 5.0.2 on 2024-02-17 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0004_cake_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='berries',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='decor',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='form',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='level',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='cake',
        ),
        migrations.RemoveField(
            model_name='words',
            name='cake',
        ),
        migrations.AddField(
            model_name='cake',
            name='words',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.words', verbose_name='Слова'),
        ),
    ]
