# Generated by Django 5.0.2 on 2024-02-17 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0005_remove_berries_cake_remove_decor_cake_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='berries',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.berries', verbose_name='Ягоды'),
        ),
        migrations.AddField(
            model_name='cake',
            name='decor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.decor', verbose_name='Декор'),
        ),
        migrations.AddField(
            model_name='cake',
            name='form',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.form', verbose_name='Форма'),
        ),
        migrations.AddField(
            model_name='cake',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.level', verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='cake',
            name='topping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='foodcartapp.topping', verbose_name='Топпинг'),
        ),
    ]
