# Generated by Django 5.0.2 on 2024-02-18 14:56

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0006_cake_berries_cake_decor_cake_form_cake_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, null=True, verbose_name='адрес'),
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата создания заказа'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_comments',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=50, null=True, verbose_name='Имейл'),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, max_length=128, null=True, region=None, verbose_name='Номер телефона'),
        ),
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.TimeField(null=True, verbose_name='Время создания заказа'),
        ),
    ]
