# Generated by Django 5.0.2 on 2024-02-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0009_order_status_alter_order_date_alter_order_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form',
            field=models.CharField(max_length=20, verbose_name='Форма'),
        ),
    ]
