# Generated by Django 5.0.2 on 2024-02-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0010_alter_form_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='form',
            field=models.CharField(choices=[('не выбрано', 'не выбрано'), ('Круг', 'Круг'), ('Квадрат', 'Квадрат'), ('Прямоугольник', 'Прямоугольник')], max_length=20, verbose_name='Форма'),
        ),
    ]
