# Generated by Django 5.0.2 on 2024-02-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0011_alter_form_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Стоимость'),
        ),
    ]
